name: geekpicker_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  dio: 4.0.4
  get_storage: 2.0.3
  animate_do: 2.1.0
  flutter_svg: 1.0.2
  cached_network_image: 3.2.0
  badges: 2.0.2
  intl: 0.17.0
  google_fonts: 2.2.0
  flutter_advanced_switch: 3.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

